### ISSUE TITLE
Clone does not always work

### ISSUE THREAD

**Issue by Matr1xxx** [sfcure/CloneOpp#2] opened 2018-12-07 08:50 UTC
Button does not work for some Opportunities with Products. We have no active validation rules and all fields are in the field set. Why does it not work? 
Manual Clone of Opportunity and clone of Products work fine. Why does the Clone with Opportunity not work for us? No error message, nothing. 
How do we know what is wrong?

**Comment by sfcure** [comment] 2019-02-21 10:57
Please try the latest version and let me know if it still happens.

**Comment by sfcure** [comment] 2019-02-25 18:07
I am closing this issue as I am not able to reproduce it with new package.

**Closed as completed by sfcure** 2019-02-25 18:07 UTC
